// The contrast budget, as it actually composites — and as a document.
//
// EPIC-02 authored the palette against a budget and asserts it token pair by
// token pair in `test/theme/contrast_budget_test.dart`. That file is the
// measurement and stays where it is. What lands here is the whole-app delta
// EPIC-14 owns and no single epic could:
//
//   * the ORACLE under seeded fuzz, rather than three pinned pairs;
//   * the `DaybreakScript` axis, which the theme builder takes and which
//     nothing had ever proved does not move a colour;
//   * `primary` as fill-only, asserted over `lib/` rather than by convention;
//   * `docs/a11y/contrast-budget.md`, regenerated by this run so the published
//     table cannot drift from the measurements behind it.
import 'dart:io';
import 'dart:math';
import 'dart:ui';

import 'package:flutter_test/flutter_test.dart';
import 'package:nearlystop/theme/daybreak_colors.dart';
import 'package:nearlystop/theme/daybreak_script.dart';
import 'package:nearlystop/theme/daybreak_theme.dart';

import '../support/contrast.dart';
import '../theme/contrast_budget_test.dart' show budget;

/// Where the published table lives.
const String kBudgetDoc = 'docs/a11y/contrast-budget.md';

/// The four palettes the app can render.
const List<(String, Brightness, bool)> _palettes = <(String, Brightness, bool)>[
  ('light', Brightness.light, false),
  ('dark', Brightness.dark, false),
  ('light high-contrast', Brightness.light, true),
  ('dark high-contrast', Brightness.dark, true),
];

void main() {
  group('the oracle, under fuzz rather than three pinned pairs', () {
    // The three published pairs in EPIC-02's file prove the formula is not
    // upside down. They do not prove it is symmetric or bounded, and a budget
    // built on an oracle that is neither measures nothing.
    test('contrast is symmetric and always inside [1, 21]', () {
      // Seeded, so a failure is reproducible from the message alone.
      final random = Random(0x0DEBA9E);

      for (var i = 0; i < 500; i++) {
        Color pick() => Color.fromARGB(
          255,
          random.nextInt(256),
          random.nextInt(256),
          random.nextInt(256),
        );
        final a = pick();
        final b = pick();
        final forward = contrastRatio(a, b);

        expect(
          forward,
          closeTo(contrastRatio(b, a), 1e-12),
          reason: 'asymmetric for $a vs $b',
        );
        expect(
          forward,
          inInclusiveRange(1, 21),
          reason: '$forward is outside [1, 21] for $a vs $b',
        );
      }
    });

    test('a colour on itself is exactly 1, at every brightness', () {
      final random = Random(0x5EED);

      for (var i = 0; i < 100; i++) {
        final c = Color.fromARGB(
          255,
          random.nextInt(256),
          random.nextInt(256),
          random.nextInt(256),
        );

        expect(contrastRatio(c, c), closeTo(1, 1e-12), reason: '$c');
      }
    });
  });

  test('the script does not move a single colour', () {
    // `buildDaybreakTheme` takes a `DaybreakScript`, so a script-specific
    // `onSurface` override could in principle slip past a palette-only
    // measurement. It cannot: the script reaches TYPE and nothing else, and
    // this is what says so. The day it stops being true, the budget above
    // needs a second axis and this test is where that is discovered.
    for (final (label, brightness, isHighContrast) in _palettes) {
      final latin = buildDaybreakTheme(
        brightness,
        DaybreakScript.latin,
        highContrast: isHighContrast,
      ).extension<DaybreakColors>()!;
      final perso = buildDaybreakTheme(
        brightness,
        DaybreakScript.perso,
        highContrast: isHighContrast,
      ).extension<DaybreakColors>()!;

      expect(perso, latin, reason: 'the script changed the palette in $label');
    }
  });

  test('primary is a FILL — never a label, never a meaningful icon', () {
    // #F97350 measures 2.76:1 on the light ground. The rule is stated in
    // `CLAUDE.md` and in the palette's own doc; this is the only thing that
    // enforces it. Matched on the ASSIGNMENT — `color: …primary` — so a
    // gradient stop or a `BoxDecoration` fill is untouched.
    final offenders = <String>[];
    final assignment = RegExp(
      r'(color|backgroundColor|foregroundColor)\s*:\s*'
      r'[A-Za-z_][A-Za-z0-9_]*\.primary\b',
    );

    for (final file
        in Directory('lib')
            .listSync(recursive: true)
            .whereType<File>()
            .where((f) => f.path.endsWith('.dart'))) {
      final lines = file.readAsLinesSync();
      for (var i = 0; i < lines.length; i++) {
        if (assignment.hasMatch(lines[i])) {
          offenders.add('${file.path}:${i + 1}: ${lines[i].trim()}');
        }
      }
    }

    expect(offenders, isEmpty);
  });

  test('the published budget table is what the run measures', () {
    // Regenerated by this test, and a stale committed table fails the build —
    // so the document cannot say one thing while the palette says another.
    final rendered = _renderBudget();
    final doc = File(kBudgetDoc);
    if (!doc.existsSync() || doc.readAsStringSync() != rendered) {
      doc
        ..createSync(recursive: true)
        ..writeAsStringSync(rendered);
      fail(
        '$kBudgetDoc was stale and has been rewritten. Read the diff, then '
        'commit it.',
      );
    }
  });
}

/// The whole budget, every palette, as the committed markdown table.
String _renderBudget() {
  final out = StringBuffer()
    ..writeln('# Contrast budget, measured')
    ..writeln()
    ..writeln(
      'Generated by `test/a11y/contrast_test.dart`. Do not edit by hand — the '
      'test rewrites this file and fails when the committed copy is stale, so '
      'a hand edit is reverted on the next run.',
    )
    ..writeln()
    ..writeln(
      'Floors: **4.5:1** body ink and meaningful icons, **3:1** marks and '
      'large display type, raised to **7:1** and **4.5:1** in the two '
      'high-contrast palettes. The sunrise gradient is the one stated '
      'exception and carries its reason in the test.',
    )
    ..writeln();

  for (final (label, brightness, isHighContrast) in _palettes) {
    final colors = daybreakColorsFor(brightness, highContrast: isHighContrast);
    out
      ..writeln('## $label')
      ..writeln()
      ..writeln('| pair | measured | floor |')
      ..writeln('|---|---:|---:|');
    for (final (name, fg, bg, baseFloor) in budget) {
      final floor = isHighContrast ? (baseFloor >= 4.5 ? 7.0 : 4.5) : baseFloor;
      final measured = contrastRatio(fg(colors), bg(colors));
      out.writeln(
        '| $name | ${measured.toStringAsFixed(2)}:1 | '
        '${floor.toStringAsFixed(1)}:1 |',
      );
    }
    out.writeln();
  }
  return out.toString();
}
