// GENERATED BY tool/gen_version.dart — DO NOT EDIT.
//
// Regenerate with `dart run tool/gen_version.dart`; CI diffs the result.

/// The app's identity, from `pubspec.yaml` at build time.
library;

/// The package name.
const String kAppPackageName = 'nearlystop';

/// The marketing version, `major.minor.patch`.
const String kAppVersion = '1.0.0';

/// The build number.
const String kAppBuildNumber = '1';

/// What the About card shows: `1.0.0 (1)`.
const String kAppVersionLabel = '$kAppVersion ($kAppBuildNumber)';
