#!/usr/bin/env bash
set -euo pipefail
# coverage_include_untested.sh — make the coverage denominator honest BEFORE
# the suite runs.
#
# `flutter test --coverage` omits files no test imports, so an untested file
# contributes zero DENOMINATOR lines rather than 0%, and one well-tested file
# can report ~100%. This generates a throwaway test that imports every lib/
# file so those files land in the denominator.
#
# Usage: bash tool/coverage_include_untested.sh
# The generated file is gitignored and must never be committed.

cd "$(dirname "$0")/.."
pkg="$(grep -E '^name:' pubspec.yaml | head -1 | awk '{print $2}')"
out=test/zzz_coverage_all_files_test.dart

{
  echo "// GENERATED by tool/coverage_include_untested.sh — do not commit."
  echo "// Imports every lib/ file so untested files count in the coverage"
  echo "// denominator. Without it the reported number lies upward."
  echo "// ignore_for_file: unused_import, directives_ordering"
  find lib -name '*.dart' \
    ! -name '*.g.dart' ! -name '*.freezed.dart' ! -name '*.drift.dart' \
    ! -path 'lib/l10n/gen/*' \
    | sort | sed -E "s#^lib/#import 'package:$pkg/#; s#\$#';#"
  echo "void main() {}"
} >"$out"

echo "coverage_include_untested: wrote $out"
