// Generates `lib/app/app_version.dart` from `pubspec.yaml`.
//
// The alternative was `package_info_plus`, which reads the same three strings
// back off the platform at runtime — and pulls `package:http` into the shipped
// binary to do it. An app whose premise is that it has no network path cannot
// carry a network client for the sake of a build-time constant.
//
// Run:  dart run tool/gen_version.dart
// CI diffs the result, exactly as it does for drift and gen-l10n.
import 'dart:io';

void main() {
  final lines = File('pubspec.yaml').readAsLinesSync();

  String field(String key) => lines
      .firstWhere(
        (line) => line.startsWith('$key:'),
        orElse: () => throw StateError('pubspec.yaml has no `$key:`'),
      )
      .substring(key.length + 1)
      .trim();

  final name = field('name');
  final parts = field('version').split('+');
  if (parts.length != 2) {
    throw StateError('pubspec `version:` must be `semver+build`, got $parts');
  }
  final semver = parts.first;
  final build = parts.last;

  File('lib/app/app_version.dart').writeAsStringSync('''
// GENERATED BY tool/gen_version.dart — DO NOT EDIT.
//
// Regenerate with `dart run tool/gen_version.dart`; CI diffs the result.

/// The app's identity, from `pubspec.yaml` at build time.
library;

/// The package name.
const String kAppPackageName = '$name';

/// The marketing version, `major.minor.patch`.
const String kAppVersion = '$semver';

/// The build number.
const String kAppBuildNumber = '$build';

/// What the About card shows: `1.0.0 (1)`.
const String kAppVersionLabel = '\$kAppVersion (\$kAppBuildNumber)';
''');
}
